### ISSUE TITLE
Contract design

### ISSUE THREAD

**Issue by robertu7** [thematters/contracts#107]
### Tasks
- [x] Confirm contract design based on [PRD and roadmap](https://paper.dropbox.com/doc/Matters-USDT--BntOxSfU7iKo9zCyIIgPjgbAAQ-hk1wXd1o4TXE86yGEsZTZ);
- [x] Output ABI design to [doc](https://www.notion.so/matterslab/USDT-Donation-c1035628b7614b54a0e926e724ded7d9);

**Comment by guoliu** [comment]
Some basic constraints and ideas: https://www.notion.so/matterslab/USDT-Donation-c1035628b7614b54a0e926e724ded7d9#ab3965ed3ed649eabbceb5223cadaeed

**Comment by robertu7** [comment]
Outputted docs: 
* [Contact ABI](https://www.notion.so/matterslab/Contact-ABI-c0ec4a50c14e48fda90fbc822abf9acc);
* [Architecture](https://www.notion.so/matterslab/Architecture-47ae28befd234632ba248d0a959951a9);
