### ISSUE TITLE
Open Source The Space

### ISSUE THREAD

**Issue by robertu7** [thematters/contracts#110]
- [x]  **GitHub**
    - [x]  https://github.com/thematters/thespace-app
    - [x]  https://github.com/thematters/thespace-landing-page
    - [x]  https://github.com/thematters/contracts
- [x]  **Proton**: mail service
- [x]  **Domain & DNS**: thespace.game

**Comment by robertu7** [comment]
https://github.com/thespace-game

**Comment by devformatters** [comment]
Looks like it's done. Feel free to reopen if it needs
