### ISSUE TITLE
[The Space Contract] refund if price higher then current price?

### ISSUE THREAD

**Issue by zxygentoo** [thematters/contracts#15]
https://github.com/thematters/contracts/blob/f608392a488a9a1ebb4b92e97d7efd5d172b7945/src/TheSpace/HarbergerMarket.sol#L121

If ```price_``` is higher than current price, shouldn't we refund sender the part above?

**Comment by guoliu** [comment]
Since the bid price needs to be higher than the asking price, `price_` is always higher than the current price. I think we can automatically set the price to the bid price (TODO) instead of refunding the sender. So price increases with bids, making it more reflective of market competitiveness.
