### ISSUE TITLE
[The Space] - Improvements on the space contract 

### ISSUE THREAD

**Issue by guoliu** [thematters/contracts#20]
- [x]  tax rate change needs an event
- [x] config variables can be put into a struct so the client can query in one call
- [x] return extra cost when the bid is higher than the price (see https://github.com/thematters/contracts/issues/15)
- [x] check ownership for `bid`, and check the price for `setPrice`
- [x] consistency error code and message, or use error type featured in 0.8.4
- [x] default timestamp for tax collection should be deploy time
- [x] update timestamp after tax collection

**Comment by zxygentoo** [comment]
- seems bid should check if tokenId is within map range (lazy mint)
- setter(Price/Color/Transfer) add more checking? eg. if new color/price is the same as old ones, don't emit event?

**Comment by zxygentoo** [comment]
@guoliu 

If it's OK, please add Xu dongjie (https://github.com/gary02) as collaborator as well. He is in charge of contract related development. thx

**Comment by gary02** [comment]
https://github.com/thematters/contracts/blob/3b0aa4fb9511614753ffef0ebb27b7900cb0177d/src/TheSpace/Property.sol#L78
Is tokenId designed to be 1 to totalSupply？IMHO， 0-base index seem be more developer-friendly.

**Comment by guoliu** [comment]
> @guoliu
> 
> If it's OK, please add Xu dongjie (https://github.com/gary02) as collaborator as well. He is in charge of contract related development. thx

Done. Welcome, @gary02!

**Comment by guoliu** [comment]
> https://github.com/thematters/contracts/blob/3b0aa4fb9511614753ffef0ebb27b7900cb0177d/src/TheSpace/Property.sol#L78
> 
> 
> Is tokenId designed to be 1 to totalSupply？IMHO， 0-base index seem be more developer-friendly.

In Solidity, 0 is the uninitialized value for uint and is sometimes used similar to "undefined" (similar with `address(0)` for address type), therefore most projects avoid using 0 as token id (one [example](https://docs.lens.dev/docs/lenshub). I think it is still a good design choice.
