### ISSUE TITLE
[Space] - Visual representation of pixel NFTs

### ISSUE THREAD

**Issue by guoliu** [thematters/contracts#40]
Each **The Space** pixel is an NFT, and there could be an associated image with it to be shown on OpenSea or any other tools that support the NFT standard. Same with the avatar in **Traveloggers**, it is the cover of the token when users check their ownership or trade particular tokens.

This image can be generated directly from the smart contract, so that it can dynamically show the current state of the token, as in the case of [Logbook 2.0](https://github.com/thematters/contracts/blob/develop/src/Logbook/Logbook.sol#L246) (can be seen on [OpenSea](https://opensea.io/collection/traveloggers-logbook)).

Information we can present in the image includes:
* color of the pixel
* price of the pixel
* UBI available for the pixel
* state of surrounding pixels
  * Note: Retrieving data on surrounding pixels is not trivial. Currently, the smart contract is not aware of the dimension of the canvas, but to identify surrounding pixels it will have to.

**Comment by devformatters** [comment]
Close it since we shipped it.
